# Generated by Django 4.2.1 on 2023-09-23 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_fund', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 15, 10, 45, 208959))),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.users')),
            ],
        ),
    ]
