# Generated by Django 4.2.1 on 2023-09-24 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_date_fund_alter_wallet_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='walletId',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_fund',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 12, 8, 21, 757827)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='userId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
