# Generated by Django 4.2.1 on 2023-06-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sname',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
