# Generated by Django 4.2.1 on 2023-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerID', models.IntegerField(unique=True)),
                ('providerName', models.CharField(max_length=20)),
            ],
        ),
    ]
